### ISSUE TITLE
[4.4] Search form date fields are too wide for the search form

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#878] opened 2019-05-08 04:37 UTC
**SS 4.4.x-dev, Chrome 74 on MacOS**

![image](https://user-images.githubusercontent.com/5170590/57349786-7fde4780-71af-11e9-833a-b66e719b4856.png)

The date pickers don't fit within their container.

I feel like there's a duplicate issue for this somewhere, sorry in advance if there is.

**Comment by brynwhyman** [comment] 2020-05-11 01:16
Closing as a duplicate of the newer https://github.com/silverstripe/silverstripe-admin/issues/1036 (as that has a PR)

**Closed by brynwhyman** 2020-05-11 01:16 UTC
Labels: affects/v4, change/patch, effort/medium, impact/medium, type/UX, type/bug
