### ISSUE TITLE
1.12 GridField relation editor JavaScript error

### ISSUE THREAD

**Issue by liefra** [silverstripe/silverstripe-admin#1427] opened 2022-12-26 05:56 UTC
## Affected Version

```
phpunit/phpunit            9.5.27 The PHP Unit Testing framework.
silverstripe-themes/simple 3.2.1  The SilverStripe simple theme (default SilverStripe 3 theme)
silverstripe/login-forms   4.8.0  A collection of templates for the CMS login screens
silverstripe/recipe-cms    4.12.0 SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-plugin 1.7.0  Helper plugin to install SilverStripe recipes
```

## Description

When using a `GridFieldConfig_RelationEditor` in combination with a `GridField` there is a JavaScript error when the relationship search and link field in the CMS. 

The search request itself gets executed correctly and there is a 200 response.
For instance the request `http://localhost:8000/admin/pages/edit/EditForm/7/field/Categories/search?gridfield_relationsearch=tr ` returns the response `[{"label":"Travel","value":"Travel","id":1}]`

But the dropdown of the relationEditor never appears and the spinner keeps spinning.

In the console there is the following error:
```js
vendor.js?m=1670898567:1 Uncaught TypeError: r.getClientRects is not a function
    at e.fn.init.offset (vendor.js?m=1670898567:1:807306)
    at Object.getWithinInfo (vendor.js?m=1670898567:1:2263439)
    at t.fn.position (vendor.js?m=1670898567:1:2263710)
    at e.fn.position (vendor.js?m=1670898567:1:2268466)
    at e.<computed>.<computed>._suggest (vendor.js?m=1670898567:1:2352878)
    at e.<computed>.<computed>._suggest (vendor.js?m=1670898567:1:2253949)
    at e.<computed>.<computed>.__response (vendor.js?m=1670898567:1:2352181)
    at e.<computed>.<computed>.__response (vendor.js?m=1670898567:1:2253949)
    at e.<computed>.<computed>.o (vendor.js?m=1670898567:1:2253833)
    at e.<computed>.<computed>.__response (vendor.js?m=1670898567:1:2354345)
```

## Steps to Reproduce

1. Use the source code of the SilverStripe many_many lesson available at: https://github.com/silverstripe/silverstripe-lessons-v4/tree/master/Lesson-10-end/app/src
2. In `ArticlePage.php` replace the `CheckboxSetField` with a `GridFieldConfig_RelationEditor`

```php

//        $fields->addFieldToTab('Root.Categories', CheckboxSetField::create(
//            'Categories',
//            'Selected categories',
//            $this->Parent()->Categories()->map('ID','Title')
//        ));

$conf = GridFieldConfig_RelationEditor::create(10);
$fields->addFieldToTab('Root.Categories', new GridField('Categories', 'Categories', $this->Categories(), $conf));
```
3. Login the CMS
4. Create sample categories
5. Create a `ArticlePage` and try to link a category

**Comment by lozcalver** [comment] 2023-01-03 09:43
Could well be related to https://github.com/silverstripe/silverstripe-admin/issues/1423 (i.e. jQuery UI needing to be updated - https://github.com/silverstripe/silverstripe-admin/pull/1424)

**Comment by ssmarco** [comment] 2023-01-09 09:53
Another way of manual testing is going to Security -> Groups section. And then click either Content Authors or Administrators from the list. From there the relation editor shows up to find existing member as shown below:
![image](https://user-images.githubusercontent.com/26287674/211281238-b3ee7756-a272-4a9a-b1e3-25c7fd3bd3c9.png)

**Comment by lekoala** [comment] 2023-01-09 10:27
Yes I can confirm I have the same issue, I'm currently looking into it

<img width="346" alt="image" src="https://user-images.githubusercontent.com/250762/211287309-7583aef6-c084-4a52-88da-477be9472a40.png">

**Comment by lekoala** [comment] 2023-01-09 10:33
in the meantime.. if you have the issue, this works after leftandmain init.

        Requirements::javascript("https://code.jquery.com/jquery-migrate-3.4.0.min.js");

**Comment by sb-relaxt-at** [comment] 2023-01-10 09:19
In case this helps someone in debugging: `r` is the window whereas I assume it should be some dom element. It seems as `this` inside the entwine function no longer points to the owning dom element. Due to the suggestion by @lekoala I assume it is related to the jQuery update.

**Comment by sb-relaxt-at** [comment] 2023-01-10 09:35
> Could well be related to #1423 (i.e. jQuery UI needing to be updated - #1424)

From my short debugging session I do agree, that seems to be the same problem.

**Comment by GuySartorelli** [comment] 2023-01-12 04:11
@liefra silverstripe/admin [1.12.1](https://github.com/silverstripe/silverstripe-admin/releases/tag/1.12.1) has been released - can you please check if that fixes this issue for you?

**Comment by liefra** [comment] 2023-01-12 04:30
@GuySartorelli : Hi, I have upgraded two projects to silverstripe/admin 1.12.1 and for both the error is gone and linking records work again as expected. Thanks a lot

**Comment by GuySartorelli** [comment] 2023-01-12 04:31
Awesome. Closing this issue then.

**Closed as completed by GuySartorelli** 2023-01-12 04:31 UTC
Labels: type/bug, affects/v4, complexity/medium, impact/medium
