### ISSUE TITLE
Use React-based TreeDropdownField in non-React sections

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#142] opened 2017-07-06 02:48 UTC
## Acceptance Criteria

 * I can select one or more items from a hierarchical structure in non-React sections of the CMS
 * The field is tested with existing uses: "Groups" in Page Settings, RedirectorPage, VirtualPage
 * The field looks and behaves the same way as in React-based sections (e.g. in "insert link")
 * The old TreeDropdownField is removed from core. There are no remaining cases where devs would need to fall back to it.
 * Any additional upgrade effort for devs is documented
 * A Behat tests exists for at least one feature path involving this field (e.g. setting a "Group" in "Page Settings")

## Notes

 * Motivation for this is consistent UX, and removing the maintenance burden of the old formfield (which has some significant complexity to it)
 * This is expected to cause zero or minimal duplication of code (JS and CSS)
 * Blocked by [Implement a TreeMultiSelectField](https://github.com/silverstripe/silverstripe-admin/issues/53) (since we want to get rid of the old field)
 * The new field is expected to have feature parity with the old one, otherwise we're breaking APIs. If that's the case, we might need to move the old field into an optional module
 * We've done a similar React/Entwine bridge through [UploadFieldEntwine.js](https://github.com/silverstripe/silverstripe-asset-admin/blob/1/client/src/entwine/UploadField/UploadFieldEntwine.js) already

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7328
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1942
- [x] https://github.com/silverstripe/silverstripe-admin/pull/214

## Related

 * [TreeDropdownField - React Search Feature](https://github.com/silverstripe/silverstripe-framework/issues/6842)
 * [Implement a TreeMultiSelectField in React](https://github.com/silverstripe/silverstripe-admin/issues/53)
 * [Convert Entwine/Chosen dropdowns to a Bootstrap React component](https://github.com/silverstripe/silverstripe-framework/issues/5670)

**Comment by chillu** [comment] 2017-07-06 02:53
@flamerohr Did I capture this correctly? Anything missing which would enable us to size this properly next week?

**Comment by flamerohr** [comment] 2017-07-06 03:05
Yeah, I think that captures most of it, perhaps add to the Notes that this is also blocked by the Search feature as well?

This could be in our DOD, but because this will carry a similar set of problems as the EntwineUploadField.js, could we add "behat tests to ensure it is functional" to the ACs so we can capture regressions that may occur in future?

**Comment by tractorcow** [comment] 2017-09-01 04:55
Feedback left on admin PR https://github.com/silverstripe/silverstripe-admin/pull/214 for you @flamerohr

**Comment by tractorcow** [comment] 2017-09-04 02:46
Merged!

**Closed by tractorcow** 2017-09-04 02:46 UTC
Labels: affects/v4, change/minor, effort/hard, impact/medium, type/enhancement, type/frontend, type/UX
