### ISSUE TITLE
React DateField's always flagged as invalid

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-admin#1772] opened 2024-06-03 21:13 UTC
### Module version(s) affected

2.2.5

### Description

It looks like for some reason DateField's rendered with React are always flagged as invalid. The value stored and passed into the validation is a proper format (YYYY-MM-DD) but the validation is still being tripped.

![image](https://github.com/silverstripe/silverstripe-admin/assets/1391558/b1363f22-a07a-417a-9e20-8496fb347437)

This maybe an upstream issue see validatorjs/validator.js#2389. There is a comment on that post that seems to indicate that the version of validator that is being used may simply be the cause of the problem. 

### How to reproduce

1. Add an extension to `SilverStripe\AssetAdmin\Forms\AssetFormFactory`
  ```php
  use SilverStripe\Control\Controller;
  use SilverStripe\Core\Extension;
  use SilverStripe\Forms\DateField;
  use SilverStripe\Forms\FieldList;
  
  class AssetFormFactoryExtension extends Extension
  {
      public function updateFormFields(FieldList $fields, Controller $controller, $formName, $context)
      {
          $fields->insertBefore(
              'ParentID',
              new DateField('ExpiryDate', 'Expiry Date'),
          );
      }
  }
  ```

2. Upload any file into the files section of asset admin using asset admin simply because it's an easy location driven by react, though the issue affects any react form including the search form in grid field.
3. With the uploaded file selected attempt to set a date in the expiry date field then move away from that control. Note the error will now be displayed.

### Possible Solution

Based on the comments in the referenced issue for `validator` a simple bump of `validator` to the latest version and rebuild may correct the problem.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1775

**Comment by GuySartorelli** [comment] 2024-06-05 02:35
I can't reproduce this - I don't get an error, and if I add a corresponding `db` field to the `File` class, it has no problem saving that data.

What interface language does the user you're testing this with have (in /admin/security)? I tested with "English (United States)" because that's the default.
For good measure, can you please paste your `composer.json` file, in case there's some minor difference in dependencies that's allowing you to reproduce it but not me?
Can you think of anything more that might help me reproduce this?

**Comment by UndefinedOffset** [comment] 2024-06-05 13:09
Hmmm very strange, I'm seeing it in both Chrome 125 and Firefox 126 on Windows 10. I'm also seeing the same on Ubuntu 22.04 with the same browser combo. One thing that may be a clue is validatorjs/validator.js#2257 the timezone of both my Ubuntu VM and Windows 10 is Atlantic (UTC-3 atm).

The user in SS is setup with "English (United States)" as well. All I'm doing is setting a date using the browser's picker and changing the focus to another field and it pops up with the error about the date being invalid. I've put a breakpoint right before the value is sent into the validator and it is showing an ISO date (i.e 2024-06-06) going into the validator call so it should pass.


composer.json
```json
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": "^8.1",
        "silverstripe/recipe-cms": "5.2.*@stable",
        "silverstripe-themes/simple": "~3.2",
        "silverstripe/login-forms": "~5.0",
        "silverstripe/userforms": "^6.0",
        "unclecheese/display-logic": "~3.0",
        "silverstripe/spamprotection": "~4.0",
        "silverstripe/blog": "~4.0",
        "silverstripe/widgets": "~3.0"
    },
    "extra": {
        "project-files-installed": [
            ".htaccess",
            "app/.htaccess",
            "app/_config.php",
            "app/_config/mimevalidator.yml",
            "app/_config/mysite.yml",
            "app/src/Page.php",
            "app/src/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "web.config"
        ]
    },
    "config": {
        "process-timeout": 600,
        "allow-plugins": {
            "composer/installers": true,
            "silverstripe/recipe-plugin": true,
            "silverstripe/vendor-plugin": true
        }
    },
    "prefer-stable": true,
    "minimum-stability": "dev",
    "require-dev": {
        "phpunit/phpunit": "~9.5",
        "squizlabs/php_codesniffer": "~3.4"
    }
}
```

**Comment by UndefinedOffset** [comment] 2024-06-05 13:41
I haven't tried updating `validatorjs/validator.js` as I've been having issues getting silverstripe/admin's yarn/npm dependencies to even install on Windows. Something about the Windows not liking installing the `@silverstripe/webpack-config` package memory serves.

I was able to get around this by passing in a Date object into the `isDate` method using this hacky Injector transform.

```javascript
Injector.transform(
    'date-field-fix',
    (updater) => {
        updater.form.addValidation(
            'AssetAdmin.*',
            (values, validationResult) => {
                if (values.ExpiryDate && validationResult.hasError('ExpiryDate')) {
                    const errors = validationResult.getErrors('ExpiryDate').filter((message) => {
                        return (/ is not a proper date format\./i.test(message) == false);
                    });

                    validationResult.clearErrors('ExpiryDate');
                    if (errors.length > 0) {
                        validationResult.addErrors({ ExpiryDate: errors });
                    }

                    if (!validationResult.hasError('ExpiryDate') && values.ExpiryDate.length > 0 && !validator.isDate(new Date(values.ExpiryDate))) {
                        validationResult.addError('ExpiryDate', 'Expiry Date is not a proper date format.');
                    }
                }
            },
        );
    },
    { after: '*' },
);
```

**Comment by GuySartorelli** [comment] 2024-06-05 22:16
I tried a new project using that `composer.json` file and changed my timezone to `Atlantic/Stanley` (just `Atlantic` got me an error when I tried to set it via DDEV). Still can't reproduce the bug.
For good measure I tried changing focus off the datefield via the mouse (clicking on another field), via keyboard (tabbing until I get to another field), hitting enter to directly save the form.... nothing I do will trigger that error for me.

Even setting a date of `01/01/0000` doesn't give me a visual error, which is somewhat concerning if there is indeed some front-end validation on-blur that's supposed to kick in.

**Comment by UndefinedOffset** [comment] 2024-06-06 12:52
It's so odd that you can't reproduce the issue I'm using `America/Halifax` as the timezone on both windows and ubuntu. Funny enough `01/01/0000` is one of the few dates that passes validation for me lol. I'm guessing the validator is treating year 0000 as the field is not populated. Is your local install using a newer version of the validator? I'm seeing 3.11.0 when my break point is hit on silverstripe/admin 2.2.5.

I checked with a couple other members of our team and they're also seeing the issue.

**Comment by GuySartorelli** [comment] 2024-06-10 03:53
> I'm seeing 3.11.0 when my break point is hit on silverstripe/admin 2.2.5.

Are you sure it's not `13.11.0`?

I don't know where the breakpoint is so I'm not 100% sure I'm looking at the same thing you are, but the output from `validator` in the dev console shows me the version is `13.11.0`

~~For completion's sake I tried setting my timezone to `America/Halifax` but no dice. Though now that I think of it, it'd probably be the browser's timezone that would affect it (if any would affect it)~~

I was changing the timezone for the server, not the client. 😮‍💨
Changing the timezone in my browser, I _can_ replicate the bug you're seeing.

**Comment by GuySartorelli** [comment] 2024-06-10 04:15
Updating the validator package seems to fix it so I'll get a PR for that soon and ask you to test it locally if you would be so kind.

**Comment by UndefinedOffset** [comment] 2024-06-10 13:14
Per my comment on the pull request the updated version appears to work as expected.

**Comment by emteknetnz** [comment] 2024-06-10 22:52
Linked PR has been merged, it will be automatically tagged shortly

**Closed as completed by emteknetnz** 2024-06-10 22:52 UTC
Labels: type/bug, impact/high, affects/v5
