### ISSUE TITLE
UploadField gets populated with wrong value

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-admin#848] opened 2019-03-18 16:23 UTC
I'm not sure if this is an admin issue or a assets issue, but here it is.

In my project, I've implemented a saveAndNext and saveAndPrevious functionnality. Everything was working fine until recently. Now, my UploadField gets populated with the value from the previous/next record (all other fields are fine though, it's only UploadField that have the issue). Only doing a full refresh will display the right value. Currently I'm only loading the "Content" section through p-jax.
Obviously, saving the record will save the value, so it's not a display issue.

My code is really simple (it's basically an extension of the ItemRequest, calling doSave and then redirecting to the next record) and I don't think there is anything wrong with it since it was working fine until then.

Any idea why the data from the UploadField would not be the good one, even after a redirect?

Tested with silverstripe 4.3.2.

**Comment by lekoala** [comment] 2019-03-18 16:29
I'm thinking it's probably the javascript that somehow keeps the state and is not refreshed upon navigation, since reloading the whole window loads the proper value, so I'm thinking it's somehow the js state that is not refreshed or is cached for the UploadField

**Comment by lekoala** [comment] 2019-03-18 17:00
Reverting to SilverStripe 4.2.4 fixes the issue, so it must be a recent change, maybe something due to the graphql endpoint.

**Comment by kinglozzer** [comment] 2019-03-19 09:23
Closing as a duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/919, thanks for reporting @lekoala

**Closed by kinglozzer** 2019-03-19 09:23 UTC

**Comment by RoyalPulp** [comment] 2022-09-12 11:01
Hello ,
 I just have exactly this issue on two projects! SilverStripe Framework 4.11.7, asset-admin 1.11.2, ...
When saving an object with an UploadField , and create a new Object, the last Image(s) is/are shown in the UploadField, that should be empty.
How can I workaround or fix this?
Thank You a lot!
Hendrik
