### ISSUE TITLE
Exception seen when importing from custom URL slug

### ISSUE THREAD

**Issue by mikenuguid** [silverstripe/silverstripe-admin#1680] opened 2024-02-16 04:12 UTC
### Module version(s) affected

1.13.22

### Description

Using `import csv` on a model admin that has a custom url slug generates an exception:  `Undefined array key`. 

### How to reproduce

* create a model admin with custom url slug
```
private static array $managed_models = [
        'link' => [
            'title' => 'Links',
            'dataClass' => Link::class,
        ],
    ];
```

* prepare some csv data to populate the model
* open the CMS and navigate on the model admin
* press `import csv`, press choose file and select the csv file containing data
* page breaks and exception seen 

### Possible Solution

This might be caused by this line https://github.com/silverstripe/silverstripe-admin/blob/1.13.22/code/ModelAdmin.php#L734 where it should be using `modelTab` instead of `modelClass`.

I haven't created a pull request yet but hopefully this is a quick fix. :)

### Additional Context

![Screenshot from 2024-02-26 12-36-30](https://github.com/silverstripe/silverstripe-admin/assets/44601742/5d01a463-02cc-4e84-8635-d8a4b65ca60c)

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1743

**Comment by GuySartorelli** [comment] 2024-02-28 22:07
I think this is a duplicate of https://github.com/silverstripe/silverstripe-admin/issues/1686 which was fixed in [1.13.23](https://github.com/silverstripe/silverstripe-admin/releases/tag/1.13.23).
Can you please check if that fixes the problem for you?

If it doesn't, please provide the full error message - and if you'd like to raise a pull request which fixes this and includes a test that would be fantastic.

**Comment by mikenuguid** [comment] 2024-02-29 01:39
Yeah it's still an issue (identical with the description above). Will create a pull request like you suggested.

**Comment by GuySartorelli** [comment] 2024-05-05 23:53
@mikenuguid Have you had a chance to look at raising a pull request for this?
If you don't raise a pull request but also don't provide the full error message (as text please, not an image), I will have to close this issue for lack of information.

**Comment by mikenuguid** [comment] 2024-05-06 01:01
Thanks for chasing, I'll find time this week.

**Comment by GuySartorelli** [comment] 2024-05-09 21:53
PR merged. This will be automatically tagged by GitHub actions.
Thanks for reporting and fixing this!

**Closed as completed by GuySartorelli** 2024-05-09 21:53 UTC
Labels: type/bug, affects/v4, impact/medium, affects/v5
