### ISSUE TITLE
IE11: TinyMCE Insert Link overrides link text with "undefined"

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1087] opened 2020-08-04 02:21 UTC
silverstripe/admin version: 1.5.1

Tested by creating a brand new silverstripe 4 installation using the silverstripe/installer recipe.
I have only seen this behaviour in IE11. Not present in Chrome or Firefox.

Steps to reproduce:

1. In the CMS. in a HTMLEditorField, select some text
1. With the text highlighted, click the "Insert link" button.
1. Select any of the link options.
1. Choose any settings within the modal that appears.
1. Click "Insert link"

The text that you highlighted is overridden with "undefined".
Note that creating a link _without_ highlighting text will correctly insert whatever is typed into the "Link text" field in the modal.

**Comment by maxime-rainville** [comment] 2020-08-05 01:16
This looks like a duplicate of https://github.com/silverstripe/silverstripe-cms/issues/2512

The issue has been fixed already but hasn't been release yet.

**Closed by maxime-rainville** 2020-08-05 01:16 UTC
