### ISSUE TITLE
Use string value instead of implode() for 2nd param of _t()

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1521] opened 2023-06-12 06:27 UTC
i18nTextCollector will throw an exception if it finds a non-string value for the 2nd param of `_t()` which is the default source value.  We have a couple of instances of `implode()` being used instead of a string value.  I think we're better off being strict here and not allowing non-string values here.

I've updated [this issue](https://github.com/silverstripe/silverstripe-framework/issues/10807) to say that this should be a become linting rule

### PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1522

**Comment by GuySartorelli** [comment] 2023-06-12 21:37
I've merged the PR because it doesn't really affect anything and unblocks you - but I'm a bit concerned that this is a new thing that the text collector is being tripped up by.

People other than just us use the text collector for their own modules and projects, so if it's throwing errors it didn't used to throw, that's a regression that we should at least log an issue for if not outright fix. Can you please raise an issue for it?

**Comment by emteknetnz** [comment] 2023-06-12 21:44
> but I'm a bit concerned that this is a new thing that the text collector is being tripped up by

I don't think it's new restriction, the `implode()` code was added for CMS 5 - it's not present in 1.13 - https://github.com/silverstripe/silverstripe-admin/blob/1.13/code/SecurityAdmin.php

I think it's only shown up now because it's the first time we've run TextCollector on CMS 5

Instead I noted on this [issue](https://github.com/silverstripe/silverstripe-framework/issues/10807) that we should lint for strings

**Comment by GuySartorelli** [comment] 2023-06-12 21:44
Ahh okay that's fine then. Closing, work is complete.

**Closed as completed by GuySartorelli** 2023-06-12 21:44 UTC
