### ISSUE TITLE
TreeDropdownField randomly shows no results

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-admin#496] opened 2018-04-18 22:26 UTC
## Environment

PHP 7.1 / Chromium 65 and Firefox 59 / silverstripe-admin 1.1 / framework 4.1.x / Ubuntu 16.04

## Scenario

I have a `TreedropdownField` that appears in a TinyMCE-invoked modal (for inserting custom links into the editor). The custom `DataObject` subclass that the menu shows instances of, totals 16,000+ items in the database, and the menu's `node_threshold_total` is set to 100. By way of comparison, I managed to also reproduce the following issue using the standard "Page on this site" TinyMCE dialogue, with the site only having 291 `SiteTree` records.

## Bug

Sometimes when the dialogue opens, and after 2 or more link insertion operations by an author, the menu will suddenly decide not to show any results; instead it displays "No results found".

## Observations:

* The AJAX call made to the custom controller (/admin/pages/edit/Modals/EditorMyCustomLink/field/MyCustomModel/tree?format=json), always returns the correct JSON, regardless of whether the menu works or not
* If in this empty state, I start typing in the menu's search-area, filtered-results will begin to be displayed again (the breadcrumbs remain disabled). Deleting the typed-in text re-enables the breadcrumbs, and allows me to navigate back up the hierarchy again (Current, "preferred" workaround).
* Also occurs using `SiteTree` items as the class for the dropdown, as evidenced from initial description above)
* There are no JS console errors

Possibly related in some way to #71 with regard to client-side caching?

**Comment by maxime-rainville** [comment] 2018-04-25 22:32
I think that might be a duplicate of #472. That one has been fixed recently but has not been release yet.

@phptek Can you have a look at that other issue and see if you're having the same problem.

**Comment by dhensby** [comment] 2018-04-27 12:39
I'm closing as a duplicate until @phptek tells us differently

**Closed by dhensby** 2018-04-27 12:39 UTC

**Comment by phptek** [comment] 2018-04-27 19:30
This certainly appears similar but the scenarios described are slightly different. This doesn't preclude the same underlying issue as being the cause for both. 

This issue should probably remain open to make it easier for others to discover. Github's default is to permit searching open issues.

**Comment by dhensby** [comment] 2018-04-30 15:26
well, @phptek the real question is can you reproduce it now the fix is merged? there's no point keeping a ticket open that we think is fixed :)

**Comment by phptek** [comment] 2018-04-30 18:39
@dhensby fair point, I had only read the description, and didn't take in that a patch had been developed. Tested branch "1.0" and it works. Question: Why is it not in branch "1.1"?

**Comment by dhensby** [comment] 2018-04-30 18:53
> Question: Why is it not in branch "1.1"?

It'll be merged up soon :)
