### ISSUE TITLE
Popover direction pointer missing

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#275] opened 2017-09-25 23:10 UTC
We are missing the pointer which indicates what a popover is linked to, there would also be the need for some space between the action and popover if there was a pointer.

From memory, we still don't have the flexibility to have the pointer positioned in different places. We will be requiring it to be positioned in the corners as well so we can place gridfield actions in the popup when the gridfield goes right up to the edge of the viewport eg.
![image](https://user-images.githubusercontent.com/555033/30835218-b000c54a-a2b3-11e7-8b32-f1edb6deaed2.png)

Bootstrap defaults:
<img width="296" alt="pasted_image_26_09_17__11_44_am" src="https://user-images.githubusercontent.com/555033/30834552-0fdc4722-a2b0-11e7-80f3-9c7d7d8949ea.png">

Our current popover:
<img width="177" alt="pasted_image_26_09_17__11_45_am" src="https://user-images.githubusercontent.com/555033/30834569-330107e2-a2b0-11e7-9ed4-7612075cf6a1.png">

**Comment by chillu** [comment] 2017-09-26 20:55
Closing as duplicate of https://github.com/silverstripe/silverstripe-admin/issues/229

**Closed by chillu** 2017-09-26 20:55 UTC
