### ISSUE TITLE
reducer transform of initial state only works with dev tools extension

### ISSUE THREAD

**Issue by blueo** [silverstripe/silverstripe-admin#390] opened 2018-01-10 19:47 UTC
I'm following the guide to set a different initial state (https://docs.silverstripe.org/en/4/developer_guides/customising_the_admin_interface/reactjs_redux_and_graphql/#setting-a-different-initial-state) but strangely, this only seems to work if you have the redux dev tools installed/active. Without that, the transformer function never gets to set the initial state. 

Putting a console.log in the transformer shows that the at some point the transformer does get a `state` variable that is `undefined` but the resulting initial state value is never set. 

I've reproduced the bug here: https://github.com/blueo/transformerbug. 
To see it in action open the asset admin section and inspect the console. With dev tools installed you should see the following:
```
index.js:6 Initial State Runs!
index.js:6 Initial State Runs!
index.js:6 Initial State Runs!
 window.ss.store.getState().assetAdmin.testVal
"I'm here!!"
```

Then disable dev tools and it shows:
```
index.js:6 Initial State Runs!
index.js:6 Initial State Runs!
 window.ss.store.getState().assetAdmin.testVal
undefined
```

It seems to log three times with dev tools and only twice without. The code looks like this:
```
/* global document */
import Injector from 'lib/Injector';

export const testTransformer = originalReducer => () => (state, { type, payload }) => {
    if (typeof state === 'undefined') {
      console.log('Initial State Runs!')
      return {
          ...originalReducer(state, { type, payload }),
          testVal: "I'm here!!",
      }
    }
    return originalReducer(state, { type, payload });
  };

document.addEventListener('DOMContentLoaded', () => {
    Injector.transform(
        'test-transformation',
        (updater) => {
          // Reducer updates
          updater.reducer('assetAdmin', testTransformer);
        },
      );
});
```

## Pull request
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/402

**Comment by chillu** [comment] 2018-01-14 19:46
@unclecheese Can you please look into this?

**Comment by tractorcow** [comment] 2018-01-17 02:09
@unclecheese I have looked into this and can reproduce it.

I have no idea what's going on with this... I need your help sorry. =(

**Comment by tractorcow** [comment] 2018-01-17 02:12
I have a feeling it's an inclusion order issue.

**Comment by flamerohr** [comment] 2018-01-17 02:26
ok, I think I see it (will test when I have time tomorrow)

You need to wrap `window.ss.store.getState().assetAdmin.testVal` with `Injector.ready(() => { });`
because you're calling the store while it's still registering and the reducer injector stuff has finished loading yet.

**Comment by tractorcow** [comment] 2018-01-17 02:32
I got this error.

```
Unexpected key "testVal" found in previous state received by the reducer. Expected to find one of the known reducer keys instead: "gallery", "queuedFiles", "uploadField", "previewField", "imageLoad". Unexpected keys will be ignored.
combination @ combineReducers.js:123
(anonymous) @ index.js:7
(anonymous) @ combineReducers.js:111
(anonymous) @ mapValues.js:15
mapValues @ mapValues.js:14
combination @ combineReducers.js:109
computeNextEntry @ VM6304:2
recomputeStates @ VM6304:2
(anonymous) @ VM6304:2
dispatch @ createStore.js:126
replaceReducer @ createStore.js:149
replaceReducer @ VM6304:2
(anonymous) @ index.js:65
(anonymous) @ buildInjectorContainer.js:69
load @ buildInjectorContainer.js:68
(anonymous) @ index.js:74
setTimeout (async)
appBoot @ index.js:74

```

**Comment by tractorcow** [comment] 2018-01-17 02:35
To get this error:
 - run all modules (mysite, admin, asset-admin) with `yarn run watch`
 - have devtools installed
 - go to admin/assets

**Comment by tractorcow** [comment] 2018-01-17 02:38
@unclecheese I think the problem is that we are modifying a combined reducer. Can you please show how we would use injector to modify a nested reducer? (e.g. modify `assetAdmin.gallery` instead of root `assetAdmin` reducer).

**Comment by tractorcow** [comment] 2018-01-17 02:51
More information on the 3 vs 2 calls. This is code I added to admin boot/index.js

```js
Injector.ready(() => {
    console.log("in injector ready");
    // add any possible new reducers that were registered
    const newReducer = combineReducers(Injector.reducer.getAll());
    store.replaceReducer(newReducer); // "Initial state runs!" called 3 times with dev tools, 2 times without
    console.log("done injector ready");

    routes.start(window.location.pathname);
    if (window.jQuery) {
      window.jQuery('body').addClass('js-injector-boot');
    }
  });
```

**Comment by tractorcow** [comment] 2018-01-17 02:54
With devtools:

```
adding in new transformer
registerReducers.js:10 registering core assetAdmin reducers
buildInjectorContainer.js:60 calling injector.load
index.js:64 in injector ready
index.js:13 Initial State Runs!
index.js:13 Initial State Runs!
index.js:66 about to replace
index.js:13 Initial State Runs!
index.js:68 done injector ready
```

**Comment by tractorcow** [comment] 2018-01-17 02:54
Without devtools

```
adding in new transformer
registerReducers.js:10 registering core assetAdmin reducers
buildInjectorContainer.js:60 calling injector.load
index.js:64 in injector ready
index.js:13 Initial State Runs!
index.js:13 Initial State Runs!
index.js:66 about to replace
index.js:68 done injector ready
```

**Comment by tractorcow** [comment] 2018-01-17 02:59
@unclecheese I think if we update the code to create the reducer in Injector.ready() instead of using replaceReducer() then it may fix it.

**Comment by flamerohr** [comment] 2018-01-17 03:05
I remember that we need `replaceReducer()` because the core reducers needed to be registered before other modules and injector is registered.
So removing it may be going too far...

**Comment by tractorcow** [comment] 2018-01-17 03:07
In applyDevTools this is being called
```
if (typeof composeExtension === 'function') {
    // use compose from extension first
    return composeExtension(middleware);
  }
```

The code is breaking if this isn't called, when dev tools isn't included.

**Comment by tractorcow** [comment] 2018-01-17 03:16
in index.js `Injector.reduce.getAll()` is called twice.

I would move everything from the first getAll() onwards to INSIDE `Injector.ready` and see if that fixes it.

**Comment by tractorcow** [comment] 2018-01-17 03:24
I tried it but I got `Uncaught Error: Cannot mutate DI container after it has been initialised`. But we ARE initialising it... argh.

**Comment by tractorcow** [comment] 2018-01-17 03:26
Maybe this would be a good example.

@flamerohr  / @unclecheese can you please review this?

https://gist.github.com/tractorcow/b44112c2dc0cc97d65ff3afa7ca83977

**Comment by blueo** [comment] 2018-01-17 03:48
This might help:
https://github.com/reactjs/redux/issues/2783

I found that the multiple calls are just coming from redux doing a sanity check on the reducer functions (specifically the the 'assertReducerSanity' function within 'combineReducers' )

The `replaceReducer` function is designed for hot module reloading/code splitting so only replaces the functions but *doesn't* re-calculate the state. As the linked issue suggests, we potentially we need another action for 'resetting' after updating the reducers.

**Comment by tractorcow** [comment] 2018-01-17 03:52
So long and short, my version (which sets the decorated reducer later, rather than setting it early and replacing it later) should fix this?

**Comment by blueo** [comment] 2018-01-17 03:58
so long as createStore is done after any injector reducers are added then yes that would work. It won't help if someone registers a reducer later - ie async - but I guess that isn't a supported case? 

Devtools calls a 'recomputeState' so that's why it is running ok when dev tools is around (https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js#L137)

**Comment by flamerohr** [comment] 2018-01-17 22:58
We could look at having a `RESET` somewhere to address this, we could potentially have this in the `Injector.reducer` API... I think we could have this in a way that module developers will not have to boilerplate a RESET.

Calling `createStore` after any injector reducers are added is just masking the symptom in my opinion.

I have the same feeling with the Injector `load()` and how it locks itself - it's bad for any async or hot-module loading that's needed, leaning toward removing the lock and investigating ways to improve performance another way.

**Comment by flamerohr** [comment] 2018-01-17 23:10
Also maybe change the scope of the `initialState` check to:
`if (typeof state === 'undefined' || typeof state.testVal === 'undefined') {`

Having that more specific check would protect you from late registrations.

**Comment by blueo** [comment] 2018-01-17 23:23
I think a 'RESET' or 'REDUCERS_REGISTERED' action is a reasonable API and would transition well if the injector became async in the future. 

I'm not sure about the scope of the initial state check. I'd prefer to follow the Redux API in which the initialState condition is when the 'state' object for a reducer === undefined. It becomes a bit murky if we start looking into individual values, especially if those values were to change as the result of a later action - perhaps it gets set to 'undefined' by another action and that would trigger an initial state load.

**Comment by flamerohr** [comment] 2018-01-18 01:15
Yes, I agree... I guess what I'm starting to see missing in a reducer transformation is scoping down levels so it doesn't need the whole bulldozer.

Maybe I'm overthinking that part.

But, I'm keen for the `RESET`/`REGISTERED` action :)

**Comment by blueo** [comment] 2018-01-18 03:43
Just did a quick action addition if it is useful: https://github.com/silverstripe/silverstripe-admin/pull/398

**Comment by flamerohr** [comment] 2018-01-18 04:41
hmm, maybe a combination of Damian's gist and your work could be used.

**Comment by flamerohr** [comment] 2018-01-22 01:50
Had a thought about it more and I'm in favour of patching this up with Damian's suggestion (with tweaks and testing) than adding a hardcoded action.

The `REGISTERED` action is nice but it'd be a bigger API change. We'll investigate hot-loading transformations later on when `Injector.load()` stops locking itself and throwing the key away.

I've raised this pull request https://github.com/silverstripe/silverstripe-admin/pull/402 with the suggestion

**Comment by tractorcow** [comment] 2018-01-22 04:40
I like #402 but I'll hold out for @unclecheese 's approval.

**Comment by tractorcow** [comment] 2018-01-24 04:51
Fixed with https://github.com/silverstripe/silverstripe-admin/pull/402

**Closed by tractorcow** 2018-01-24 04:51 UTC
Labels: affects/v4, change/patch, effort/hard, impact/high, type/bug, type/frontend
