### ISSUE TITLE
Change Tracker not respecting .no-change-track class

### ISSUE THREAD

**Issue by chrispenny** [silverstripe/silverstripe-admin#350] opened 2017-11-10 00:58 UTC
Setting up a `GridField` with a basic `RelationEditor` config. As soon as you start typing into the search field the edit form flags itself as changed.

```php
$config = GridFieldConfig_RelationEditor::create();

// create a Checkbox group based on the array
$fields->addFieldToTab(
    'Root.Settings',
    GridField::create(
        'DataObjects',
        'My Data Objects',
        $this->owner->DataObjects(),
        $config
    )
);
```

![screen shot 2017-11-10 at 1 41 58 pm](https://user-images.githubusercontent.com/505788/32637448-b6d66382-c61e-11e7-97d5-fac5198762d8.png)

I realise this seems like a very minor issue, but in our current project (using Fluent) we very much do **not** want authors to save the page in this situation - as saving the Page will create a localised of that Page.

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/362
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/391

**Comment by mfendeksilverstripe** [comment] 2017-12-14 23:05
@tractorcow This issue needs to be re-opened as it has not been fixed properly. While the functionality works fine for the initial page load, after user switches to a different tab and back the issue is still there (no-change-track components change the save and publish button states).

**Comment by chrispenny** [comment] 2017-12-14 23:13
I switch to a different tab:
![screen shot 2017-12-15 at 12 10 23 pm](https://user-images.githubusercontent.com/505788/34018905-10a125a4-e191-11e7-9b1e-48cee276b2e3.png)

I switch back to a tab containing a field with `no-change-track`:
![screen shot 2017-12-15 at 12 10 33 pm](https://user-images.githubusercontent.com/505788/34018913-1d6e8f24-e191-11e7-98a4-2b0855f17c11.png)

I enter a value into the field and then `blur`:
![screen shot 2017-12-15 at 12 10 41 pm](https://user-images.githubusercontent.com/505788/34018923-26fa2cba-e191-11e7-9e53-217c389a8f93.png)

We're also seeing this occur in other GridFields that have a dropdown menu.

**Comment by tractorcow** [comment] 2018-01-08 00:13
It seems ok to me @chrispenny 

![image](https://user-images.githubusercontent.com/936064/34655849-9ef2e31e-f475-11e7-8f33-9c0b0d4ea506.png)

Can you ensure you're using admin 1.0.1?

**Comment by tractorcow** [comment] 2018-01-08 00:14
Maybe I need to test with more tabs?

**Comment by chrispenny** [comment] 2018-01-08 01:40
Thanks, @tractorcow - we will retest and let you know. Possibly something else in our setup is causing the issue.

CC: @mfendeksilverstripe.

**Comment by chrispenny** [comment] 2018-01-11 20:02
@tractorcow it's possible that our example above is more specific to our project, as I wasn't able to replicate the issue with the Fluent field specifically, but I am still able to replicate a similar issue with vanilla SS4 and a `has_many` `Image` `GridField`.

## Enter the `Page`:
![screen shot 2018-01-12 at 8 55 25 am](https://user-images.githubusercontent.com/505788/34844554-c4b8f0a8-f776-11e7-9a93-d9820221b61f.png)

## Enter a search value, about to select result:
![screen shot 2018-01-12 at 8 55 34 am](https://user-images.githubusercontent.com/505788/34844580-d87ac026-f776-11e7-8084-c839e3cf89b5.png)

## Result selected, still focused in the search field:
![screen shot 2018-01-12 at 8 55 40 am](https://user-images.githubusercontent.com/505788/34844601-e3107b84-f776-11e7-82e3-6f26328d099a.png)

## Search field blurred:
![screen shot 2018-01-12 at 8 55 48 am](https://user-images.githubusercontent.com/505788/34844610-eab672bc-f776-11e7-9f89-16a7369558d7.png)

# Project set up.

## `composer.json`
```
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "^1",
        "silverstripe/recipe-cms": "1.0.1@stable",
        "silverstripe-themes/simple": "~3.2.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^5.7",
        "silverstripeltd/vagrant": "dev-master"
    },
    "extra": {
        "project-files-installed": [
            ".htaccess",
            "index.php",
            "install-frameworkmissing.html",
            "install.php",
            "mysite/.htaccess",
            "mysite/_config.php",
            "mysite/_config/mysite.yml",
            "mysite/code/Page.php",
            "mysite/code/PageController.php",
            "web.config"
        ]
    },
    "config": {
        "process-timeout": 600
    },
    "prefer-stable": true,
    "minimum-stability": "dev",
    "repositories": {
        "vagrant": {
            "type": "git",
            "url": "https://github.com/silverstripeltd/silverstripe-vagrant.git"
        }
    }
}
```

## `Page.php`:
```php
<?php

use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Forms\GridField\GridField;

class Page extends SiteTree
{
    private static $db = [];

    private static $has_one = [];

    private static $has_many = [
        'Images' => \SilverStripe\Assets\Image::class,
    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $fields->addFieldsToTab(
            'Root.Images',
            [
                $images = GridField::create('Image', 'Image', $this->Images()),
            ]
        );

        $config = $images->getConfig();
        $config->addComponent(new \SilverStripe\Forms\GridField\GridFieldAddExistingAutocompleter());

        return $fields;
    }
}
```

## `ImageExtension.php`:
```php
<?php

namespace MySite\Extension;

use SilverStripe\ORM\DataExtension;

class ImageExtension extends DataExtension
{
    private static $has_one = [
        'Page' => \Page::class,
    ];
}
```

## `mysite.yml`:
```yml
---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite

SilverStripe\Assets\Image:
  extensions:
    - MySite\Extension\ImageExtension
```

**Comment by tractorcow** [comment] 2018-01-11 21:32
Assigning to self I'll try to reproduce it later.

**Comment by tractorcow** [comment] 2018-01-12 03:48
Fix at https://github.com/silverstripe/silverstripe-admin/pull/391

**Closed** 2018-01-15 01:37 UTC
Labels: affects/v4, change/minor, effort/medium, impact/low, type/bug
