### ISSUE TITLE
HTMLEditorField breaking in inline edit

### ISSUE THREAD

**Issue by dizzystuff** [silverstripe/silverstripe-admin#1519] opened 2023-06-09 03:48 UTC
I can't tell whether this is a `silverstripe-admin` bug, or a `silverstripe-elemental` bug, or otherwise. I can dig further but would much appreciate any thoughts on that. Happy to post over there too, or move it over entirely.

I'm logging this here initially, because my hunch after reviewing the commit histories of each is that the issue could lie in `silverstripe-admin:1.13.x`.

The most recent version combination that _does not_ break is `silverstripe-elemental:4.11.0` with `silverstripe-admin:1.12.7`. I suspect `elemental:4.11.1` would be fine except that it requires `admin:1.13.2`.

Symptoms of "breaking/not working" are that any toolbar button that display a modal/popup or menu, no longer appear to trigger their popup or menu. From what I've been able to tell, the markup for the menu/popups is being added to the dom but potentially in the wrong area, and are missing css/js that would otherwise position it correctly.

- I have a `Page` with an `ElementalArea`. 
- I have an element type `ElementTwoCol` which contains two `ElementalArea`s
- I add an `ElementTwoCol` to the `Page` via its `ElementalArea` field, with inline_editing disabled
- I click the new `ElementTwoCol` to be taken to its Edit Form page/url
- In the form now on screen, showing `ElementTwoCol->getCMSFields()`'s fields/form, I have two elemental area fields, one for each "column" area
- I add an `ElementContent` to either of these elem area fields, and click the element to reveal the inline editing form
- At this point, the `HTMLEditorField` breaks / isn't working
- Though I've not replicated this, client has mentioned that sometimes it will work on the initial create, but after saving it breaks as described.

This _does not_ occur, when the elemental area field is being displayed within a `Page`'s cms fields. This is only when the elemental area field's container is not a `Page`. It is not limited to `ElementContent`, it occurs for any inline element form containing a `HTMLEditorField`.

<img width="797" alt="sshot" src="https://github.com/silverstripe/silverstripe-admin/assets/576903/6acdb2b5-5a26-44de-bce6-caaf43c47d13">

**Comment by maxime-rainville** [comment] 2023-06-11 22:22
Duplicate of https://github.com/silverstripe/silverstripe-admin/issues/1512

**Closed as completed by maxime-rainville** 2023-06-11 22:22 UTC
Labels: type/bug, affects/v4, impact/medium
