### ISSUE TITLE
React Driven UIs don't render in Silverstripe 5

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-admin#1494] opened 2023-04-05 12:46 UTC
It looks like for some reason mostly React driven UI's such as Files and Campaigns do not seem to be rendering. There is no error in the JavaScript console in Chrome or Firefox, just nothing happens when the page loads.

composer.json:
```json
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": "^8.1",
        "silverstripe/recipe-plugin": "^2",
        "silverstripe/vendor-plugin": "~2.0.0@stable",
        "silverstripe/recipe-cms": "~5.0.0@rc",
        "silverstripe-themes/simple": "~3.2.0",
        "silverstripe/login-forms": "~5.0.0@rc"
    },
    "require-dev": {
        "phpunit/phpunit": "^9.5"
    },
    "extra": {
        "project-files-installed": [
            ".htaccess",
            "app/.htaccess",
            "app/_config.php",
            "app/_config/mimevalidator.yml",
            "app/_config/mysite.yml",
            "app/src/Page.php",
            "app/src/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "web.config"
        ]
    },
    "config": {
        "process-timeout": 600,
        "allow-plugins": {
            "composer/installers": true,
            "silverstripe/recipe-plugin": true,
            "silverstripe/vendor-plugin": true
        }
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}
```

Note: hosting platform is Windows 10, with Apache and PHP 8.2.

**Comment by michalkleiner** [comment] 2023-04-06 00:29
Is it also when you have the install in a subfolder or does it not work for you even when the site is in the root of a domain?

**Comment by michalkleiner** [comment] 2023-04-06 00:29
Please note that Silverstripe CMS and other modules in the ecosystem are not yet supporting PHP 8.2, so there's no guarantee things will work.

**Comment by UndefinedOffset** [comment] 2023-04-06 12:46
It looks like it does work when the install is in the doc root, so perhaps it's related to #1495? It looks like the request for `admin/_graphql/admin.types.graphql` goes out but after that it stops. In the case of the campaign admin it never attempts `admin/campaigns/schema/EditForm`, and in the case of files it never attempts the post to `admin/graphql`.

As for PHP 8.2, anecdotally other than the two issues I've filed it seems to be working at least at a high level. I haven't tried anything too complex just a base install and very very quick testing of a couple of my own modules.

**Comment by michalkleiner** [comment] 2023-04-06 14:32
I think the culprit here is the `<base>` tag for the CMS itself and it will be the same for #1495, yes. Working in a subdir is in theory supported but might present issues like this.

**Comment by GuySartorelli** [comment] 2023-04-10 22:52
I'm going to close this as it sounds like the root cause is #1495

**Closed as completed by GuySartorelli** 2023-04-10 22:52 UTC
