### ISSUE TITLE
CMS 5: console error whenever a toast pops up

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1412] opened 2022-12-11 21:01 UTC
https://github.com/silverstripe/silverstripe-admin/issues/1312 results in some regressions which we've decided to handle as separate issues. This is one of those.

Whenever a toast pops up that has a dismiss button, there is a console error complaining about the "onDismiss" prop. Most likely this only happens when the javascript is built in dev mode (i.e. `yarn dev`, not `yarn build`).

This is a very minor problem, but it could potentially lead to a problem later down the line if react gets more strict about its props.

## Acceptance criteria
- [ ] There are no console errors or warnings about toasts

## PRs
-

**Comment by sabina-talipova** [comment] 2023-03-07 20:34
I could not reproduce this issue in my local environment. Probably, it has been already solved.
I close this issue, but I'll open it again while I'm working on [this issue](https://github.com/silverstripe/silverstripe-admin/issues/1416), if it will appear.

**Closed as completed by sabina-talipova** 2023-03-07 20:34 UTC
Labels: type/bug, complexity/medium, impact/low, affects/v5

**Comment by sabina-talipova** [comment] 2023-03-08 20:17
I've got console error on test execution:
```
    console.error
      Warning: Failed prop type: The prop `toasts[0].onDismiss` is marked as required in `Toasts`, but its value is `undefined`.
          in Toasts

      36 |     it('One toast', () => {
      37 |       const handlers = getHandlers();
    > 38 |       const wrapper = shallow(<Toasts toasts={[toastOne]} {...handlers} />);
         |                               ^
      39 |
      40 |       expect(wrapper.props()).toMatchObject({
      41 |         className: 'toasts',

      at printWarning (node_modules/prop-types/checkPropTypes.js:20:15)
      at checkPropTypes (node_modules/prop-types/checkPropTypes.js:83:11)
      at validatePropTypes (node_modules/react-16/cjs/react.development.js:1714:7)
      at Object.createElementWithValidation [as createElement] (node_modules/react-16/cjs/react.development.js:1813:5)
      at Object.<anonymous> (client/src/components/Toasts/tests/Toasts-test.js:38:31
```
