### ISSUE TITLE
Broken loading indicators in the CMS

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#750] opened 2018-11-09 03:10 UTC
# Overview

Loading indicators no longer work, which makes the CMS seem unresponsive, particularly on larger installations with longer loading times

# Steps to Reproduce

 * Click on a page in the tree

# Context

 * Chrome v70 , Firefox v61
 * 4.3 (potentially earlier)

# Notes

 * Please check how far back this bug goes, and fix it in the earliest branch
 * [Loading indicator patterns](https://github.com/silverstripe/silverstripe-admin/issues/176)

# Pull Request
* [x] #756

**Comment by robbieaverill** [comment] 2018-11-12 10:43
I just noticed this in CWP 2.2 regression testing. Thanks, will reference this issue.

**Comment by maxime-rainville** [comment] 2018-11-19 22:36
Loading indicator is still working in 4.2. So the issue looks 4.3 specific. The problem seems to affect ModelAdmins as well as CMSMain. I'll start looking into admin to begin with.

**Comment by maxime-rainville** [comment] 2018-11-19 22:52
J'accuse!!! https://github.com/silverstripe/silverstripe-admin/pull/74

Looks like this PR change the entwine selector for picking up the loading indicator. Switching back to `onmatch` fixes the issue. I'll try to see what the change was trying to fix and see if we need to have an `onmatch` and `onadd`.

**Comment by maxime-rainville** [comment] 2018-11-20 22:30
Fixed by #756.

**Closed by maxime-rainville** 2018-11-20 22:30 UTC
Labels: affects/v4, effort/medium, impact/critical, type/bug
