### ISSUE TITLE
Change sass-lint for stylelint

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1437] opened 2023-01-11 21:24 UTC
[sass-lint](https://github.com/sasstools/sass-lint) is abandoned - its recommended replacement is [stylelint](https://github.com/stylelint/stylelint)

This was originally upgraded as part of the change to the frontend build stack, though this was later reverted as stylelint is currently non-functional due to the lack of stylelintrc.yml files

We need to change all the sass-lint.yml files in modules to stylelintrc.yml files instead i.e. https://dev.to/stories_of_ren/switching-from-sass-lint-to-stylelint-5f8c

This should probably only be done for CMS5

### Related
- https://github.com/silverstripe/webpack-config/issues/69

### ACs
- Update silverstripe/webpack-config from sass-lint to stylelint
- yarn update all modules that use webpack-config
- Add stylelintrc.yml files to modules
  - If this requires a lot of configuration, that configuration is added to a separate NPM package which we can reference from all modules, similar to https://github.com/silverstripe/eslint-config/
- Remove sass-lint.yml files from modules
- Linting passes without errors or warnings on all core and supported modules

**Comment by GuySartorelli** [comment] 2024-04-23 01:09
Closing as duplicate of https://github.com/silverstripe/webpack-config/issues/69

**Closed as not planned by GuySartorelli** 2024-04-23 01:09 UTC
Labels: type/enhancement, affects/v5
