### ISSUE TITLE
update jQuery/entwine ?

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-admin#493] opened 2018-04-17 16:15 UTC
I realize that the idea is to promote react for the javascript side of things, however I find myself often developing  components that should be used in the backend (admin) and in the front end (where other technologies than react might be used). For that, using jQuery is perfect.

However I recently realized that it's still jQuery version 1.7.2 that is used in the admin. Should jQuery be at least upgraded to the latest version in the 1.x branch? It would be easier to support a lot of plugins that don't work with older versions of jQuery (for instance, ParsleyJS require jQuery > 1.8, but I have a few others : Select2, Inputmask...). Or to make this version somehow configurable?

Also, to promote usage across back and front office, it would be nice to have a simple way to require entwine as well. The only small issue with entwine is the usage of $.support that has been deprecated in jQuery 1.9 but quite easy to fix. 

Any thoughts on that? Or should I definitely drop jquery/entwine and focus on using react?

**Comment by dhensby** [comment] 2018-04-17 16:31
duplicate of https://github.com/silverstripe/silverstripe-framework/issues/3384

**Closed by dhensby** 2018-04-17 16:31 UTC
