### ISSUE TITLE
Bootstrap 4.0 upgrade

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#433] opened 2018-02-13 03:11 UTC
# Overview

We're currently on Bootstrap 4.0.0-beta, and a [Reactstrap](https://github.com/silverstripe/silverstripe-admin/issues/415) upgrade necessitates an upgrade to Bootstrap 4.0.0 stable. 

# Acceptance Criteria

 * CMS uses Bootstrap 4.0.0
 * All CMS bootstrap uses are regression tested (with a good mix across our supported browsers)
 * Any design variations are checked with Jared or Paul
 
# PRs:

See https://github.com/silverstripe/silverstripe-admin/issues/415 for PR list

**Comment by chillu** [comment] 2018-02-13 03:12
Copying comments from @lukereative:

> At the moment SS4 is using Bootstrap 4.0.0-beta and the compatible reactstrap version is 4.8.0, if we wanted we could upgrade to Bootstrap 4.0.0 (stable) and use reactstrap 5.0.0-beta. There have been a few changes from Bootstrap 4.0.0-beta into stable that affect us:

>    Slight change in badge colour behaviour
>    A change in structure of option and checkbox form fields
>    A change in structure of input addons
>    Popover changed js libraries from tether to poppers, but this doesn't seem to change functionality overall
>    Active states colours seem to have changed as well so this will need to be checked

> I think there might be a few others that will come out of the woodwork but looking at the bootstrap docs for their listed breaking beta changes they were fairly minimal. Overall it doesn't seem like too much extra effort and this seems like a good time to do it.

@lukereative Can you please add a points estimate to this card?

**Comment by robbieaverill** [comment] 2018-02-13 03:25
Duplicate of https://github.com/silverstripe/silverstripe-admin/issues/395, closing that one in favour of this one

**Comment by tractorcow** [comment] 2018-02-28 00:09
Closing in favour of #415. Admin module has been updated to latest bootstrap.

**Closed by tractorcow** 2018-02-28 00:09 UTC
Labels: affects/v4, change/minor, effort/medium, impact/high, type/enhancement, type/frontend
