### ISSUE TITLE
Cannot get CMS to detect Custom Stylesheet

### ISSUE THREAD

**Issue by EEKimS** [silverstripe/silverstripe-admin#513] opened 2018-05-05 05:26 UTC
Hi there,

I am still wrapping my head around SS4, and struggling a bit - so i might be missing something obvious!

From everything i have found, i should be able to load custom CSS by using this code:

**mysite/css/admin-styles.css**
```
/* test style - for an obvious sign it loaded */
.cms-menu {
    background-color: blue!important;
}
```

**app.yml**
```
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - mysite/css/admin-styles.css
```

I have run /dev/build, and ?flush=all on the front and back end, cleared my cache, etc just in case there was something that wasn't loaded, but sadly no luck.

My hope is to style the CMS to a dark theme, as the pale interface can cause migraines after many hours of use

**Comment by maxime-rainville** [comment] 2018-05-07 01:13
@EEKimS I just tried a similar example to yours on SS4x it works fine for me.

Silly question here, but have you switch to using the `public` web-root?

**Comment by EEKimS** [comment] 2018-05-07 14:39
@maxime-rainville Yes, this is a new setup on SS4.1, but i am still learning where everything goes. 
Is there a folder i should have this in that should work?
For some reason my set up just will not load it, and i am not sure where to look yet to debug it

**Comment by maxime-rainville** [comment] 2018-05-07 22:13
@EEKimS That's probably the problem. If you are using the public webroot, your `mysite` folder is no longer directly accessible via your webserver.

There's a couple ways you can fix this. The recommended way is to move your CSS file under the `public` folder. So `mysite/css/admin-styles.css` would be rename to `public/css/admin-styles.css`. Then update your `extra_requirements_css` entry to `css/admin-styles.css`.

Alternatively, you can expose your `mysite` folder by adding the following code snippet to your 1composer.json1 file and calling `composer vendor-expose`.
```json
{
...
  extra: {
    "expose": [
      "mysite"
    ]
  }
...
}

However, this would defeat the purpose of using the public webroot.

[Have a read through the SS4.1 changelogs](https://docs.silverstripe.org/en/4/changelogs/4.1.0/#upgrade-public-folder-optional) for more information about how to make your static assets accessible publicly through your web server.

I'll close this issue as this is the intended behavior, but let us know if you need more info or if come across some other unexpected behavior.

**Closed by maxime-rainville** 2018-05-07 22:13 UTC
Labels: affects/v4, change/patch, effort/easy, impact/low, type/bug

**Comment by EEKimS** [comment] 2018-05-08 05:01
@maxime-rainville Ahh right, i knew i was missing something fairly obvious, i moved the css into the public folder, and it all pulls through now, thank you very much for your help :)
