### ISSUE TITLE
1.12 horizontal scrollbar in split mode

### ISSUE THREAD

**Issue by tiller1010** [silverstripe/silverstripe-admin#1430] opened 2023-01-06 14:22 UTC
This PR removed a style rule that prevented horizontal scrollbars when in split mode:
https://github.com/silverstripe/silverstripe-admin/pull/1422

The scrollbar **does not** show in Firefox, but it does show in Brave and Edge.

### Firefox
![firefox](https://user-images.githubusercontent.com/42498429/211030221-5fbece45-f58b-4aa2-bdaf-518f9fa61c0d.png)

### Brave
![brave](https://user-images.githubusercontent.com/42498429/211030224-0a55e163-6173-42d0-be7d-881adbe672c1.png)

### Edge
![edge](https://user-images.githubusercontent.com/42498429/211030227-a12a161b-734d-43a3-818e-81a3fff804a8.png)

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1629

**Comment by StevenLantinga** [comment] 2023-01-25 08:33
For anybody wondering: This is caused by the mode dropdown itself in the right bottom. Adding `#preview-mode-dropdown-in-content .chosen-drop { right: 0; width: 160px; }` fixed the issue.

**Comment by RVXD** [comment] 2023-07-07 08:47
I guess this would be a minor change to fix? Issue has been open since jan 6. Is there any way I can help?
One note: the issue is also visible in non-split mode, so maybe change title of issue.

**Comment by lerni** [comment] 2023-07-07 18:31
Use :fire::fox_face::exclamation: :grinning:
To make the suggested fix above also work in preview-mode, I figured
```css
/* in 5.x we need to revert #7b430d4 and add the previous snippet bellow
https://github.com/silverstripe/silverstripe-admin/commit/7b430d4171da9608918190109b85e15260e0d626 */
.chosen-container:not(.chosen-container-active) {
	overflow: hidden;
}

.preview-mode-selector .chosen-drop {
	width: inherit;
	right: 0;
}
```
If that looks acceptable I would try do make build-env working, PR and also test it a bit more. To what branch:question: If 4.x, is build than done on up-merge for 5?

**Comment by RVXD** [comment] 2023-11-30 11:31
Can this be implemented? Now all CMS's have a horizontal scrollbar. This is still visible in 5.1.

**Comment by GuySartorelli** [comment] 2023-11-30 19:57
Because this is a very minor visual bug, the CMS Squad can't dedicate time to fixing this right now. If this is causing problems for you, I recommend opening a pull request that fixes it.

**Comment by RVXD** [comment] 2023-12-01 08:39
Hi Guy, it is also a bug that is simple to fix, without much time/effort. I don't understand why you skip fixing these 'minor bugs' so easily. I will look into how to make a PR for a CSS change. This probably involves building the CSS from SCSS?

**Comment by GuySartorelli** [comment] 2023-12-01 08:46
There are a _lot_ of low impact bugs that would be quick to fix on their own - but if we tried to do all of them we wouldn't have much time to dedicate to high impact bugs or enhancements. 

Low impact but easy to fix bugs are great opportunities for the community to provide contributions for exactly the reason that they won't (again, in isolation) take long to fix.

Yup, building the CSS from SCSS is necessary if you're doing a CSS change. There's information about how to do that in the contribution docs, but let me know if you get stuck.

**Comment by RVXD** [comment] 2023-12-01 08:54
I understand, will look into it! Thanks, Guy.

**Comment by RVXD** [comment] 2023-12-01 15:24
Nice work @lerni ! I tried it on:
Mac OSX: Chrome, Safari, Firefox
Windows: Chrome and Edge
Before this fix only in FF it was working without scrollbar, after this fix there is also no horizontal scrollbar in Chrome, Safari and Edge.

**Comment by tiller1010** [comment] 2023-12-01 17:24
The solution from @lerni works for me, but I think it should be noted that this style is only necessary for browsers other than firefox. That way it doesn't get removed again.

**Comment by GuySartorelli** [comment] 2024-01-23 22:13
PR merged. This will be automatically tagged by GitHub actions

**Closed as completed by GuySartorelli** 2024-01-23 22:13 UTC
Labels: type/bug, affects/v4, impact/low, type/UX
