### ISSUE TITLE
1.2.x - private static $menu_icon has no effect

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-admin#558] opened 2018-07-03 10:52 UTC
Looks like a regression from https://github.com/silverstripe/silverstripe-admin/pull/412.

[`LeftAndMain::menu_icon_for_class()`](https://github.com/silverstripe/silverstripe-admin/blob/1.2.0-beta1/code/LeftAndMain.php#L913-L929) returns CSS for the menu icons, but it wasn’t updated as part of the above PR.

The classes (in `LeftAndMain_MenuList.ss`) have changed from:

`menu__icon icon icon-16 icon-{$Icon}`
to
`menu__icon font-icon-circle-star font-icon-{$Icon}`

I guess that means that the generated CSS won’t work even if the classes are updated, as the icon font uses pseudo-elements

**Comment by lekoala** [comment] 2018-07-31 16:45
I can confirm this is indeed not working in 4.2

Either old 16px should be removed entirely, or the MenuList template should allow them to be used.

**Comment by dajeinc** [comment] 2018-08-08 20:47
I am running into this problem. Any solution?

**Comment by lekoala** [comment] 2018-08-09 07:26
The solution is overriding the template SilverStripe/Admin/Includes/LeftAndMain_MenuList.ss with the content of version 4.1 and ensure you have the proper css loaded by the admin

```
<ul class="cms-menu__list">
	<% loop $MainMenu %>
		<li class="$LinkingMode $FirstLast <% if $LinkingMode == 'link' %><% else %>opened<% end_if %>" id="Menu-$Code" title="$Title.ATT">
			<a href="$Link" $AttributesHTML>
				<% if IconClass %>
					<span class="menu__icon $IconClass"></span>
				<% else %>
					<span class="menu__icon icon icon-16 icon-{$Icon}">&nbsp;</span>
				<% end_if %>
				<span class="text">$Title</span>
			</a>
		</li>
	<% end_loop %>
</ul>
```

```
.menu__icon.icon-16 {
    left: 14px;
    background-repeat: no-repeat;
}

@media (min-width: 768px) {
    .collapsed .menu__icon.icon-16 {
        left: 22px;
    }
}

```

**Comment by baukezwaan** [comment] 2018-08-23 08:08
The solution above would not be complete, as LeftAndMain classes without any icons set ($menu_icon or $menu_icon_class) wouldn't have a fallback. These should show the circle-star image...

Another work-around would be changing the menu_icon_for_class function to:

`return ".menu__icon.font-icon-{$class} { background-image: url('{$iconURL}'); width:16px; height:16px;} .menu__icon.font-icon-{$class}:before{ content: none;}";`

But that's kind of dirty, better option would be to add a third option to the template (LeftAndMain_MenuList.ss) where the circle-star would be added as fallback.

**Comment by ScopeyNZ** [comment] 2018-12-04 21:45
Closed by #770

**Comment by ScopeyNZ** [comment] 2018-12-04 21:45
Please feel free to reopen if this hasn't addressed the issues discussed here 🙂

**Closed by ScopeyNZ** 2018-12-04 21:45 UTC
Labels: affects/v4, impact/low, type/bug, type/frontend

**Comment by UndefinedOffset** [comment] 2018-12-13 14:00
It looks like it did address the issue for 1.2.3 (SilverStripe 4.2.3) but it doesn't seem to have made the 1.3.0 tag (SilverStripe 4.3.0).

**Comment by kinglozzer** [comment] 2018-12-13 15:21
Yeah it missed the window for 1.3.0, the commit is in the `1` branch - looks like we need to merge it down to the `1.3` branch though?

**Comment by UndefinedOffset** [comment] 2018-12-13 15:23
I think it maybe in the 1.3 branch as commit ab012a6559fa8cef467fd7b5f5a380b796745a53 ([see](https://github.com/silverstripe/silverstripe-admin/blob/1.3/templates/SilverStripe/Admin/Includes/LeftAndMain_MenuList.ss) it just missed the 1.3.0 tag :)

**Comment by kinglozzer** [comment] 2018-12-13 15:38
Oh good, that’ll teach me for trusting Github’s UI!

<img width="580" alt="screenshot 2018-12-13 at 15 37 26" src="https://user-images.githubusercontent.com/1655548/49949241-17838680-feed-11e8-8c7f-acc03cb33c3f.png">

**Comment by ScopeyNZ** [comment] 2018-12-13 20:56
Yeah we tagged `1.3.0` from the RC with a couple of critical bugfixes - sorry I know that's not very clear. I imagine we'll be tagging a 4.3.1 before too long.

**Comment by NightJar** [comment] 2019-02-28 21:45
It looks like this [missed 1.3.1](https://github.com/silverstripe/silverstripe-admin/commits/1.3.1) as well, can someone _please_ merge this up?

**Comment by robbieaverill** [comment] 2019-02-28 21:58
@NightJar note that the 4.3.1 release was security only. The branches are merged up and this will be released with the next patch release.

**Comment by NightJar** [comment] 2019-02-28 22:07
Thanks @robbieaverill - but I don't see the fixing commit in the `1.3` branch.

**Comment by robbieaverill** [comment] 2019-02-28 22:45
ab012a6 is in the 1.3 branch, it's just not in the 1.3.1 tag =)
