### ISSUE TITLE
TreeMultiselectField not appearing correctly in CMS Admin Settings

### ISSUE THREAD

**Issue by oilee80** [silverstripe/silverstripe-admin#379] opened 2017-12-12 16:30 UTC
This can be seen with the ViewerGroups & EditorGroups field in the Settings tab

![image](https://user-images.githubusercontent.com/1453382/33895691-fa0dcdea-df58-11e7-89ba-fe2c5ba77c33.png)

It appears to be due to one too many wrapping divs getting styled but not fully looked into it yet

**Comment by kinglozzer** [comment] 2017-12-12 17:10
Duplicate of https://github.com/silverstripe/silverstripe-admin/issues/377

**Closed by kinglozzer** 2017-12-12 17:10 UTC
