### ISSUE TITLE
Popover (for Elemental) too narrow (1.7 regression) 

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-admin#1156] opened 2020-11-13 15:36 UTC
The popover used for displaying available Elemental blocks appears to have become too narrow in 1.7 causing block names to become truncated.

**1.6**
<img width="497" alt="Screenshot 2020-11-13 at 15 21 49@2x" src="https://user-images.githubusercontent.com/329880/99089687-8a0fac00-25c5-11eb-8a86-fd7d1cb17160.png">

**1.7**
<img width="433" alt="Screenshot 2020-11-13 at 15 22 35@2x" src="https://user-images.githubusercontent.com/329880/99089698-8c720600-25c5-11eb-882f-653d3c62fbf9.png">

Also, note the more obvious cut off top corners.

As per https://github.com/dnadesign/silverstripe-elemental/issues/848 I believe this is related to work done for the Reactstrap 8 upgrade. But unsure if resolving it is just a cause of increasing the new min-width: https://github.com/silverstripe/silverstripe-admin/blob/5d179b734ed1f97a0f3c853e29539e971c6988f5/client/src/components/PopoverOptionSet/PopoverOptionSet.scss#L15

## Acceptance Criteria
- This has been tested across a range of device sizes

**Comment by kinglozzer** [comment] 2021-01-27 10:42
Looks to me like the `max-width` we set [here](https://github.com/silverstripe/silverstripe-admin/blob/5d179b734ed1f97a0f3c853e29539e971c6988f5/client/src/components/PopoverOptionSet/PopoverOptionSet.scss#L5) and [here](https://github.com/silverstripe/silverstripe-admin/blob/5d179b734ed1f97a0f3c853e29539e971c6988f5/client/src/components/PopoverOptionSet/PopoverOptionSet.scss#L11) need to also be copied into the nested `.popover` selector. Currently the `max-width` is less than the `min-width`!

**Comment by maxime-rainville** [comment] 2021-02-11 20:58
Fixed by https://github.com/silverstripe/silverstripe-admin/pull/1174

**Comment by maxime-rainville** [comment] 2021-02-16 04:15
Looks like the fix has broken the popover even worst https://github.com/silverstripe/silverstripe-admin/pull/1174#issuecomment-779564409

Marking as critical because it looks really bad now

**Comment by thats4shaw** [comment] 2021-02-16 04:31
@maxime-rainville I'm using Chrome Version 88.0.4324.146.

It seems from my initial investigation that it gets worse the more items you have.

**Comment by maxime-rainville** [comment] 2021-02-16 04:33
Do you mean the more blocks you have in your elemental Area ... or do you mean block options you have in the popover?

**Comment by thats4shaw** [comment] 2021-02-16 04:36
Well both right?  More blocks allowed to be used in the elemental area means more items in popover.

**Comment by maxime-rainville** [comment] 2021-02-16 04:44
Got it. Managed to replicate the problem by adding a bunch of dummy blocks.

![image](https://user-images.githubusercontent.com/1168676/108019213-9d2b8f80-707e-11eb-8a80-87efcd223782.png)

**Comment by michalkleiner** [comment] 2021-02-16 04:54
> Do you mean the more blocks you have in your elemental Area ... or do you mean block options you have in the popover?

> Well both right? More blocks allowed to be used in the elemental area means more items in popover.

Not so much both, just the latter. The problem is with the number of block types, not the number of block instances in the area.

**Comment by Cheddam** [comment] 2021-02-22 21:19
A fix has been shipped in silverstripe/admin 1.7.3. There isn't yet a recipe release that includes this version, but we hope to get one out in the next week or so. In the meantime, you can adopt the fix directly by aliasing it in your Composer configuration:

```
    "silverstripe/admin": "1.7.3 as 1.7.2",
```

Thanks all!

**Closed by Cheddam** 2021-02-22 21:19 UTC
Labels: affects/v4, change/patch, effort/easy, impact/critical, type/bug
