### ISSUE TITLE
Re-enable ability to auto select a tab from a URL anchor

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#911] opened 2019-07-18 15:14 UTC
**SS 4**

I want to deep link to a GridField item's Settings tab (for example). Allegedly you used to be able to do this by appending `#Root_Settings` to the URL for it (maybe in SS3?), which would detect the anchor in the URL and automatically set it as the active tab.

This doesn't work in SS 4.4.x - there's a todo example [here](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Security/Group.php#L231-L237) which indicates that it didn't work when that comment was written either.

At some stage this jQuery UI interface is probably going to be React driven anyway, but this might be a nice quick win addition in the meantime.

## PR's
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/1030/files
- [ ] ~https://github.com/silverstripe/silverstripe-admin/pull/986~

**Comment by kinglozzer** [comment] 2019-07-18 15:18
Confirmed this feature used to exist - it works on a 3.7.3 site

**Comment by robbieaverill** [comment] 2019-07-18 15:39
How should this work with nested tab sets? Could I do `#Root_Content-Submissions` or something to open Content > Submissions for a userforms page for example?

**Comment by kinglozzer** [comment] 2019-07-18 15:46
That’s a good question. I just checked in 3.7.3 and it doesn’t work at all...

I suppose ideally the anchor would still match the ID, so you can right click and copy a link to the nested tab. Do nested tabsets already generate IDs like your example?

**Comment by robbieaverill** [comment] 2019-07-18 15:48
The root tabset doesn't have an ID like that either as far as I can tell - it's `ui-id-3` etc, with a numeric index which is presumably specific to jQuery UI's handling of the tabs when it runs

**Comment by robbieaverill** [comment] 2019-07-26 11:47
I can't get this to work with pages (by trying `#Root_Settings`), or within a Member's GridField edit form (by trying `#Root_Permissions`) on SS 3.7.x.

In the jQuery UI library there is the following logic which should enable this functionality for us:

```js
		if ( active === null ) {
			// check the fragment identifier in the URL
			if ( locationHash ) {
				this.tabs.each(function( i, tab ) {
					if ( $( tab ).attr( "aria-controls" ) === locationHash ) {
						active = i;
						return false;
					}
				});
			}
```

In SS 4.x at least, this code does fire but at the point where it runs the `aria-controls` attributes haven't been added to the DOM yet, so it can't find a matching tab for the `locationHash`. If this logic were to be deferred until the `DOMContentLoaded` event, then it would work correctly.

**Comment by robbieaverill** [comment] 2019-07-26 12:20
Alright, looks like `ss-tabset` classes were removed from a lot of the PHP and templates, possibly with the intention of using `cms-tabset` instead. Adding the `ss-tabset` classes back has some success, but I'll see if switching the JS to use `.cms-tabset` instead might help too. 

There are a lot of places where tabs are used, and they're all slightly different forms and contexts. I'm focussing primarily on GridFieldDetailForm's at the moment. ModelAdmin's would be nice to have as well, as would the CMS.

**Comment by robbieaverill** [comment] 2019-07-26 12:29
I've had some success with this patch, but haven't completed enough testing yet to PR it:

```patch
diff --git a/client/src/legacy/TabSet.js b/client/src/legacy/TabSet.js
index b0314bc..8730cc7 100644
--- a/client/src/legacy/TabSet.js
+++ b/client/src/legacy/TabSet.js
@@ -11,7 +11,7 @@ $.entwine('ss', function($){
        /**
         * Lightweight wrapper around jQuery UI tabs for generic tab set-up
         */
-       $('.ss-tabset').entwine({
+       $('.cms-tabset').entwine({
                IgnoreTabState: false,
 
                onadd: function() {
```

**Comment by chillu** [comment] 2019-08-08 00:03
This is affecting our ability to create a new product demo now, since we can't deep link to the features we're describing in the CMS (e.g. being forced to link to `admin/settings` instead of `admin/settings/<colour-picker-tab>`)

**Comment by normann** [comment] 2019-08-27 21:59
It effect one of our SS modules as well, could anyone manage to test the @robbieaverill 's fixes and tackle the issue, please?

**Comment by mlewis-everley** [comment] 2019-10-04 14:32
Being able to deep link to CMS tabs would be a really useful addition to something I am working on as well.

**Comment by robbieaverill** [comment] 2019-10-04 16:39
@mlewis-everley you can workaround in custom code if you want, not pretty but it works. See https://github.com/dnadesign/silverstripe-elemental/issues/701

**Comment by mlewis-everley** [comment] 2019-10-04 16:48
@robbieaverill Thanks for the info. I have tried to get your patch working on a Framework only install and your change to Tabset.js appears to work, but once implemented, every time you try to visit a `ModelAdmin` interface I get a "Bed Request" error appear in the top right (in one of the popup messages).

Inspecting the XHR request reveals a 400 error ("Ajax requests to this URL require an X-Pjax header.").

It looks like SS4 has removed some request headers that SS3 was using, I guess now that Tabset.js is looking for the correct classnames, it is calling some other JS that expects different headers?

**Comment by mlewis-everley** [comment] 2019-10-31 12:01
OK, I have done some more work on this. I *think* that the `redrawTabs` method in `TabSet.js` may be part of the issue I am seeing with `ModelAdmin`.

I am working on a PR for the 1.3 branch as the 1.2 version of the code looks quite different and I don't have a project to test it on (plus trying to work out the correct versions to install everything at can be a total pain).

The main things I have had to change are:

1. Remove `redrawTabs`, as this seems to work using `redrawTabs` defined in `LeftAndMain.js`.
2. Switch the `ss-tabset` selector to `cms-tabset`.
3. Change `onadd` to `onmatch` (for some reason `onadd` doesn't work for me).

Hopefully I will have a PR up sometime today.

**Closed** 2020-09-03 22:06 UTC
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/bug
