### ISSUE TITLE
Untranslatable js text `Search options`

### ISSUE THREAD

**Issue by pschiffe** [silverstripe/silverstripe-admin#1689] opened 2024-02-24 18:44 UTC
### Module version(s) affected

2.1.17

### Description

Hello, there is an untranslatable text `Search options` in js file `SearchBox.js`:
https://github.com/silverstripe/silverstripe-admin/blob/50751546b57f32b66f8a173d64daa03d017d80ae/client/src/components/Search/SearchBox.js#L292C35-L292C49

Also, some texts are not in transifex.com, such as `Admin.SEARCH` or `Admin.ADVANCED`.

Cheers

### How to reproduce

Check source code.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1692

**Comment by pschiffe** [comment] 2024-02-24 19:22
There's also this text I'm not able to translate or find out where it's coming from:

![Screenshot 2024-02-24 at 20-20-03 Jedáleň - Správa jedál](https://github.com/silverstripe/silverstripe-admin/assets/3899107/159c6126-ff19-42bb-90df-f37cb1acae9c)

Locally I see it only in the file `vendor/silverstripe/admin/client/dist/js/vendor.js`

**Comment by GuySartorelli** [comment] 2024-02-25 23:24
> there is an untranslatable text Search options in js file SearchBox.js

Thanks for reporting this. Would you like to submit a pull request to fix this? There are examples in that same file of how to make the string localisable.
If it affects CMS 4 the PR should target the `1.13` branch, otherwise target the `2.1` branch.

> Also, some texts are not in transifex.com, such as Admin.SEARCH or Admin.ADVANCED.

Please open a separate issue for this - the root cause is completely different and so needs to be handled separately.

> There's also this text I'm not able to translate or find out where it's coming from

This is coming from a third-party package. Please create a separate issue about this, including more details such as what type of field that is, and the PHP code used to initialise that field.

**Comment by GuySartorelli** [comment] 2024-03-04 21:17
PR merged. This will be automatically tagged by GitHub actions.

**Closed as completed by GuySartorelli** 2024-03-04 21:17 UTC
Labels: type/bug, impact/low, affects/v5
