### ISSUE TITLE
IE11 - Changing value of HTMLField causes JS error

### ISSUE THREAD

**Issue by HJGreen** [silverstripe/silverstripe-admin#913] opened 2019-07-23 08:38 UTC
## Affected versions
`silverstripe/admin` **1.4.1**
`silverstripe/framework` **4.4.1**

## Steps to reproduce

- Open a page which contains a HTMLField in the SilverStripe admin panel
- Open IE Developer Tools (errors aren't logged unless open)
- Type some characters into the TinyMCE editor

Developer tools should pause execution of the JavaScript and log the following error to the console:

```
SCRIPT445: Object doesn't support this action
File: bundle.js, Line: 3623, Column: 105
```
where `bundle.js` is `vendor/silverstripe/admin/client/dist/js/bundle.js`

## Cause

The line linked below tries to execute `new Event(...)` which is not supported in IE11:

https://github.com/silverstripe/silverstripe-admin/blob/f4913c5e52d1cf9cd87700bf5f4698eab827a5c1/client/src/legacy/HtmlEditorField.js#L101

The `save` function which contains that line appears to be bound to the editor's `change` event.

The error occurs silently if developer tools are not open, however it still breaks JS execution and can cause issues elsewhere

**Comment by robbieaverill** [comment] 2019-07-23 08:52
Thanks for reporting this issue. I'm going to close as a duplicate of https://github.com/silverstripe/silverstripe-cms/issues/2459

**Closed by robbieaverill** 2019-07-23 08:52 UTC

**Comment by HJGreen** [comment] 2019-07-23 08:54
Thanks @robbieaverill - I had a search in this repo, but didn't check the CMS module!

**Comment by robbieaverill** [comment] 2019-07-23 08:54
No problem, it's very segmented. You can use https://silverstripe-github-issues.now.sh/ to do multi-repo searches.
