### ISSUE TITLE
Update the demo of SilverStripe 4

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#55] opened 2017-05-07 23:04 UTC
The demo is way out of date and should be available for the community to provide feedback. This could also be used as a testing ground without the risk of major breaking changes which are common in test sites.
https://www.silverstripe.org/4/

**Comment by chillu** [comment] 2017-05-08 00:01
Yeah I've been spending about a day battling this already - the problem is that it's pretty much the first deployment of SS4 on SSP, there was lots of kinks to iron out.

**Comment by chillu** [comment] 2017-06-01 02:44
@robbieaverill Stig has been moving this to a different stack, just FYI

**Comment by chillu** [comment] 2017-06-08 02:06
Yay, Stig got this over the line now! https://ss4-demo.silverstripe.org/

**Closed by chillu** 2017-06-08 02:06 UTC
Labels: affects/v4, change/patch, type/UX
