### ISSUE TITLE
vendor.js attempts to read the ID of every element in the DOM

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-admin#1583] opened 2023-09-15 07:03 UTC
3rd party javascripts injecting DOM elements without an ID, e.g. a Maps search fly-out, will throw kilometers of errors in the console.

**Comment by GuySartorelli** [comment] 2023-09-17 22:17
Thank you for reporting that.
Can you please provide more information? Do you know which third party scripts specifically are causing this? Can you provide an example of the error(s) that are occurring?
Also, does this affect and functionality or is the problem on that it is reporting errors in the console?

**Comment by GuySartorelli** [comment] 2023-09-22 02:48
I have been unable to reproduce this - I'm going to close it for now, but if you can provide more details I'll be happy to reopen it and try again.

**Closed as not planned by GuySartorelli** 2023-09-22 02:48 UTC
